# Data statistics

```{r load_data_stats}
load("data/data.Rdata")
```
```{r}
read_counts <- read_tsv("data/counts.tsv") %>%
    rename(genome=1) %>% 
    rename_with(~ str_remove(.x, "_EKDL.*")) %>% 
    rename_with(~ str_remove(.x, "_M$"))%>%
  select(one_of(c("genome",sample_metadata$sample))) %>%
  filter(rowSums(. != 0, na.rm = TRUE) > 0) %>%
  select_if(~!all(. == 0)) 
```

```{r}
seq <-read_counts %>% 
  column_to_rownames(., "genome") %>% 
  colSums() %>% 
  as.data.frame() %>% 
  rename(seq=".") %>% 
  arrange(seq)
```

## Sample overview 

```{r}
sample_metadata %>% 
  nrow()
```
```{r}
sample_metadata %>% 
  group_by(country) %>% 
  summarise(count=n())
```

```{r}
sample_metadata <- sample_metadata %>%
  mutate(country = if_else(country == "Shangai domestic dog", "Shangai", country)) %>% 
  mutate(
    dog_type = case_when(
      breed == "Wolf"        ~ "wolf",
      country == "Greenland" ~ "sled_dog",
      TRUE                   ~ "domestic"
    )
  )
sample_metadata %>% 
  group_by(dog_type) %>% 
  summarise(count=n())
```