# AMR and VF

```{r load_data_amr, comment="", message=FALSE, warning=FALSE}
load("data/data.Rdata")
load("data/alpha_all.Rdata")
genome_metadata <- genome_metadata %>% 
  mutate(phylum = case_when(
        phylum == "Bacillota_A" ~ "Bacillota",
        phylum == "Bacillota_C" ~ "Bacillota",
        phylum == "Bacillota_B" ~ "Bacillota",
        phylum == "Bacillota_I" ~ "Bacillota",
        TRUE ~ phylum))

remove_sled <- read_csv("data/sample_metadata.csv") %>% 
  filter(season=="winter")

sample_metadata <- sample_metadata %>%
  mutate(country = if_else(country == "Shangai domestic dog", "Shangai", country)) %>% 
  filter(!sample %in% remove_sled$sample) %>%
  mutate(
    dog_type = case_when(
      breed == "Wolf"        ~ "wolf",
      country == "Greenland" ~ "sled_dog",
      TRUE                   ~ "domestic"
    )
  )%>%
  mutate(
    dog_group = case_when(
      breed == "Wolf" ~ "wolf",
      locality == "Disko" ~ "civilian",
      locality == "Daneborg" ~ "military",
      locality == "Illulissat" ~ "civilian",
      locality == "Ittoqqortoormiit" ~ "civilian",
      TRUE                   ~ "domestic"
    )
  )

genome_counts_filt <- genome_counts_filt %>%
  select(one_of(c("genome",sample_metadata$sample)))%>%
  filter(rowSums(. != 0, na.rm = TRUE) > 0) %>%
  select_if(~!all(. == 0))

genome_metadata <- genome_metadata %>%
  semi_join(., genome_counts_filt, by = "genome") %>%
  arrange(match(genome,genome_counts_filt$genome))

genome_tree <- keep.tip(genome_tree, tip=genome_metadata$genome)
```
```{r load_genome_annotations, warning=FALSE, comments="", message=FALSE}
genome_annotations <- read_tsv("data/gene_annotations.tsv.xz") %>%
  mutate(genome = str_extract(gene, "^[^^]+")) %>%
  mutate(ec = str_c("[EC:",ec,"]")) %>% 
  select(genome, everything())
```

## Genome size

```{r size_per_sample, warning=FALSE, comments="", message=FALSE}
sample_genome_size <- genome_counts_filt %>% 
  mutate(across(-genome,~ .x / sum(.x, na.rm = TRUE))) %>% 
  inner_join(genome_metadata %>% select(genome,length), by = "genome") %>%
  pivot_longer(
    cols = -c(genome, length),
    names_to  = "sample",
    values_to = "rel_abundance"
  ) %>%
  group_by(sample) %>%
  summarise(
    size = weighted.mean(length, w = rel_abundance, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  left_join(sample_metadata,by="sample")
```

**Country**
```{r}
sample_genome_size %>% 
  group_by(country) %>%
  summarise(
    mean = mean(size, na.rm = T)/1000000,
    sd = sd(size, na.rm = T)/1000000) %>% 
  arrange(-mean) %>% 
  mutate(genome_size=str_c(round(mean,3),"±",round(sd,3))) %>% 
  select(country,genome_size) 
```
```{r}
sample_genome_size %>%
  kruskal_test(size ~ country) %>% 
  adjust_pvalue(method = "BH") %>%
  filter(p.adj < 0.05) %>% 
  tt()
```

```{r}
sample_genome_size %>%
  wilcox_test(size ~ country, p.adjust.method = "BH")%>% 
  filter(p.adj < 0.05)
```

```{r}
sample_genome_size %>%
  wilcox_test(size ~ country, p.adjust.method = "BH")%>% 
  filter(p.adj > 0.05)
```

```{r size_per_sample_plot_country, warning=FALSE, comments="", message=FALSE, fig.height=5, fig.width=10, fig.fullwidth=TRUE}
sample_genome_size %>%
  ggplot(aes(x = country, y = size, color = country, fill = country)) +
  geom_jitter(width = 0.2, alpha=0.5, show.legend = FALSE) +
  geom_boxplot(width = 0.5, alpha=0.3,outlier.shape = NA, show.legend = FALSE) +
  theme_classic() +
  theme(
    axis.text = element_text(face = "bold", size = 12),
    strip.background = element_blank(),
    axis.title.y = element_text(face = "bold", size = 14, margin = margin(t = 0, r = 20, b = 0, l = 0)),
    axis.title.x = element_blank()
    )
```

**Dog type**
```{r}
sample_genome_size %>% 
  group_by(dog_type) %>%
  summarise(
    mean = mean(size, na.rm = T)/1000000,
    sd = sd(size, na.rm = T)/1000000) %>% 
  arrange(-mean) %>% 
  mutate(length=str_c(round(mean,3),"±",round(sd,3))) %>% 
  select(dog_type,length) 
```

```{r}
sample_genome_size %>%
  kruskal_test(size ~ dog_type) %>% 
  adjust_pvalue(method = "BH") %>%
  filter(p.adj < 0.05) %>% 
  tt()
```

```{r}
sample_genome_size %>%
  wilcox_test(size ~ dog_type, p.adjust.method = "BH")%>% 
  filter(p.adj < 0.05)
```

```{r}
sample_genome_size %>%
  wilcox_test(size ~ dog_type, p.adjust.method = "BH")%>% 
  filter(p.adj > 0.05)
```

**Civilian vs Military**
```{r}
sample_genome_size %>% 
  group_by(dog_group) %>%
  summarise(
    mean = mean(size, na.rm = T)/1000000,
    sd = sd(size, na.rm = T)/1000000) %>% 
  arrange(-mean) %>% 
  mutate(genome_size=str_c(round(mean,3),"±",round(sd,3))) %>% 
  select(dog_group,genome_size) 
```

```{r}
sample_genome_size %>%
  kruskal_test(size ~ dog_group) %>% 
  adjust_pvalue(method = "BH") %>%
  filter(p.adj < 0.05) %>% 
  tt()
```

```{r}
sample_genome_size %>%
  wilcox_test(size ~ dog_group, p.adjust.method = "BH")%>% 
  filter(p.adj < 0.05)
```

```{r}
sample_genome_size %>%
  wilcox_test(size ~ dog_group, p.adjust.method = "BH")%>% 
  filter(p.adj > 0.05)
```

```{r size_per_sample_plot, warning=FALSE, comments="", message=FALSE, fig.height=5, fig.width=8, fig.fullwidth=TRUE}
sample_genome_size %>%
  ggplot(aes(x = dog_type, y = size, color = dog_type, fill = dog_type)) +
  geom_jitter(width = 0.2, alpha=0.5, show.legend = FALSE) +
  geom_boxplot(width = 0.5, alpha=0.3,outlier.shape = NA, show.legend = FALSE) +
  theme_classic() +
  theme(
    axis.text = element_text(face = "bold", size = 12),
    strip.background = element_blank(),
    axis.title.y = element_text(face = "bold", size = 14, margin = margin(t = 0, r = 20, b = 0, l = 0)),
    axis.title.x = element_blank()
    )
```

## AMR

```{r amr_per_genome, warning=FALSE, comments="", message=FALSE}
genome_amr <- genome_annotations %>% 
  group_by(genome) %>%
  summarise(AMR = sum(resistance_type == "AMR", na.rm = TRUE), .groups = "drop")
```

```{r amr_per_sample, warning=FALSE, comments="", message=FALSE}
sample_amr <- genome_counts_filt %>% 
  mutate(across(-genome,~ .x / sum(.x, na.rm = TRUE))) %>% 
  inner_join(genome_amr, by = "genome") %>%
  pivot_longer(
    cols = -c(genome, AMR),
    names_to  = "sample",
    values_to = "rel_abundance"
  ) %>%
  group_by(sample) %>%
  summarise(
    AMR = weighted.mean(AMR, w = rel_abundance, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  left_join(sample_metadata,by="sample")
```

**Country**
```{r}
sample_amr %>% 
  group_by(country) %>%
  summarise(
    mean = mean(AMR, na.rm = T),
    sd = sd(AMR, na.rm = T)) %>% 
  arrange(-mean) %>% 
  mutate(AMR=str_c(round(mean,3),"±",round(sd,3))) %>% 
  select(country,AMR) 
```

```{r amr_per_locality_plot, warning=FALSE, comments="", message=FALSE, fig.height=5, fig.width=8, fig.fullwidth=TRUE}
sample_amr %>% 
  ggplot(aes(x=country,y=AMR,color=country,fill=country)) +
  geom_jitter(width = 0.2, alpha=0.5, show.legend = FALSE) +
  geom_boxplot(width = 0.5, alpha=0.3,outlier.shape = NA, show.legend = FALSE) +
  theme_classic() +
  theme(
    axis.text = element_text(face = "bold", size = 12),
    strip.background = element_blank(),
    axis.title.y = element_text(face = "bold", size = 14, margin = margin(t = 0, r = 20, b = 0, l = 0)),
    axis.title.x = element_blank()
    )
```
```{r}
sample_amr %>%
  kruskal_test(AMR ~ country) %>% 
  adjust_pvalue(method = "BH") %>%
  filter(p.adj < 0.05) %>% 
  tt()
```

```{r}
sample_amr %>%
  wilcox_test(AMR ~ country, p.adjust.method = "BH")%>% 
  filter(p.adj < 0.05)
```
```{r}
sample_amr %>%
  wilcox_test(AMR ~ country, p.adjust.method = "BH")%>% 
  filter(p.adj > 0.05)
```

**Domestic vs sled vs wolf**
```{r}
sample_amr %>% 
  group_by(dog_type) %>%
  summarise(
    mean = mean(AMR, na.rm = T),
    sd = sd(AMR, na.rm = T)) %>% 
  arrange(-mean) %>% 
  mutate(AMR=str_c(round(mean,3),"±",round(sd,3))) %>% 
  select(dog_type,AMR) 
```


```{r amr_per_group_plot, warning=FALSE, comments="", message=FALSE, fig.height=4, fig.width=8, fig.fullwidth=TRUE}
sample_amr %>% 
  ggplot(aes(x=dog_type,y=AMR,color=dog_type,fill=dog_type)) +
  geom_jitter(width = 0.2, alpha=0.5, show.legend = FALSE) +
  geom_boxplot(width = 0.5, alpha=0.3,outlier.shape = NA, show.legend = FALSE) +
  theme_classic() +
  theme(
    axis.text = element_text(face = "bold", size = 12),
    strip.background = element_blank(),
    axis.title.y = element_text(face = "bold", size = 14, margin = margin(t = 0, r = 20, b = 0, l = 0)),
    axis.title.x = element_blank()
    )
```

```{r}
sample_amr %>%
  kruskal_test(AMR ~ dog_type) %>% 
  adjust_pvalue(method = "BH") %>%
  filter(p.adj < 0.05) %>% 
  tt()
```

```{r}
sample_amr %>%
  wilcox_test(AMR ~ dog_type, p.adjust.method = "BH")%>% 
  filter(p.adj < 0.05)
```

Civilian & Military
```{r}
sample_amr %>% 
  group_by(dog_group) %>%
  summarise(
    mean = mean(AMR, na.rm = T),
    sd = sd(AMR, na.rm = T)) %>% 
  arrange(-mean) %>% 
  mutate(AMR=str_c(round(mean,3),"±",round(sd,3))) %>% 
  select(dog_group,AMR) 
```

```{r}
sample_amr %>%
  kruskal_test(AMR ~ dog_group) %>% 
  adjust_pvalue(method = "BH") %>%
  filter(p.adj < 0.05) %>% 
  tt()
```

Significant
```{r}
sample_amr %>%
  wilcox_test(AMR ~ dog_group, p.adjust.method = "BH")%>% 
  filter(p.adj < 0.05)
```

Non-sig
```{r}
sample_amr %>%
  wilcox_test(AMR ~ dog_group, p.adjust.method = "BH")%>% 
  filter(p.adj > 0.05)
```

```{r amr_per_doggroup_plot, warning=FALSE, comments="", message=FALSE, fig.height=4, fig.width=8, fig.fullwidth=TRUE}
sample_amr %>% 
  mutate(dog_group=factor(dog_group,levels=c("domestic","civilian","military", "wolf"))) %>%
  ggplot(aes(x=dog_group, y=AMR, color=dog_group, fill=dog_group)) +
  geom_jitter(width = 0.2, alpha=0.5, show.legend = FALSE) +
  geom_boxplot(width = 0.5, alpha=0.3,outlier.shape = NA, show.legend = FALSE) +
  theme_classic() +
  theme(
    axis.text = element_text(face = "bold", size = 12),
    strip.background = element_blank(),
    axis.title.y = element_text(face = "bold", size = 14, margin = margin(t = 0, r = 20, b = 0, l = 0)),
    axis.title.x = element_blank()
    )
```

## Virulence factors

```{r vf_per_genome, warning=FALSE, comments="", message=FALSE}
genome_vf <- genome_annotations %>% 
  group_by(genome) %>%
  summarise(vf = sum(!is.na(vf_type), na.rm = TRUE), .groups = "drop")

sample_vf <- genome_counts_filt %>% 
  mutate(across(-genome,~ .x / sum(.x, na.rm = TRUE))) %>% 
  inner_join(genome_vf, by = "genome") %>%
  pivot_longer(
    cols = -c(genome, vf),
    names_to  = "sample",
    values_to = "rel_abundance"
  ) %>%
  group_by(sample) %>%
  summarise(
    vf = weighted.mean(vf, w = rel_abundance, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  left_join(sample_metadata,by="sample")
```

**Country**
```{r}
sample_vf %>% 
  group_by(country) %>%
  summarise(
    mean = mean(vf, na.rm = T),
    sd = sd(vf, na.rm = T)) %>% 
  arrange(-mean) %>% 
  mutate(virulence=str_c(round(mean,3),"±",round(sd,3))) %>% 
  select(country,virulence) 
```

```{r vf_per_locality_plot, warning=FALSE, comments="", message=FALSE, fig.height=5, fig.width=10, fig.fullwidth=TRUE}
sample_vf %>% 
  ggplot(aes(x=country,y=vf,color=country,fill=country)) +
  geom_jitter(width = 0.2, alpha=0.5, show.legend = FALSE) +
  geom_boxplot(width = 0.5, alpha=0.3,outlier.shape = NA, show.legend = FALSE) +
  theme_classic() +
  theme(
    axis.text = element_text(face = "bold", size = 12),
    strip.background = element_blank(),
    axis.title.y = element_text(face = "bold", size = 14, margin = margin(t = 0, r = 20, b = 0, l = 0)),
    axis.title.x = element_blank()
    )
```
```{r}
sample_vf %>%
  kruskal_test(vf ~ country) %>% 
  adjust_pvalue(method = "BH") %>%
  filter(p.adj < 0.05) %>% 
  tt()
```

```{r}
sample_vf %>%
  wilcox_test(vf ~ country, p.adjust.method = "BH")%>% 
  filter(p.adj < 0.05)
```
```{r}
sample_vf %>%
  wilcox_test(vf ~ country, p.adjust.method = "BH")%>% 
  filter(p.adj > 0.05)
```

**Domestic vs sled vs wolf**
```{r}
sample_vf %>% 
  group_by(dog_type) %>%
  summarise(
    mean = mean(vf, na.rm = T),
    sd = sd(vf, na.rm = T)) %>% 
  arrange(-mean) %>% 
  mutate(virulence=str_c(round(mean,3),"±",round(sd,3))) %>% 
  select(dog_type,virulence) 
```

```{r vf_per_group_plot, warning=FALSE, comments="", message=FALSE, fig.height=5, fig.width=8, fig.fullwidth=TRUE}
sample_vf %>% 
  ggplot(aes(x=dog_type,y=vf,color=dog_type,fill=dog_type)) +
  geom_jitter(width = 0.2, alpha=0.5, show.legend = FALSE) +
  geom_boxplot(width = 0.5, alpha=0.3,outlier.shape = NA, show.legend = FALSE) +
  theme_classic() +
  theme(
    axis.text = element_text(face = "bold", size = 12),
    strip.background = element_blank(),
    axis.title.y = element_text(face = "bold", size = 14, margin = margin(t = 0, r = 20, b = 0, l = 0)),
    axis.title.x = element_blank()
    )
```

```{r}
sample_vf %>%
  kruskal_test(vf ~ dog_type) %>% 
  adjust_pvalue(method = "BH") %>%
  filter(p.adj < 0.05) %>% 
  tt()
```

```{r}
sample_vf %>%
  wilcox_test(vf ~ dog_type, p.adjust.method = "BH")
```

**Civilian & Military**
```{r}
sample_vf %>% 
  group_by(dog_group) %>%
  summarise(
    mean = mean(vf, na.rm = T),
    sd = sd(vf, na.rm = T)) %>% 
  arrange(-mean) %>% 
  mutate(virulence=str_c(round(mean,3),"±",round(sd,3))) %>% 
  select(dog_group,virulence) 
```
```{r vf_per_military_plot, warning=FALSE, comments="", message=FALSE, fig.height=5, fig.width=8, fig.fullwidth=TRUE}
sample_vf %>% 
  ggplot(aes(x=dog_group,y=vf,color=dog_group,fill=dog_group)) +
  geom_jitter(width = 0.2, alpha=0.5, show.legend = FALSE) +
  geom_boxplot(width = 0.5, alpha=0.3,outlier.shape = NA, show.legend = FALSE) +
  theme_classic() +
  theme(
    axis.text = element_text(face = "bold", size = 12),
    strip.background = element_blank(),
    axis.title.y = element_text(face = "bold", size = 14, margin = margin(t = 0, r = 20, b = 0, l = 0)),
    axis.title.x = element_blank()
    )
```

```{r}
sample_vf %>%
  kruskal_test(vf ~ dog_group) %>% 
  adjust_pvalue(method = "BH") %>%
  filter(p.adj < 0.05) %>% 
  tt()
```

Significant
```{r}
sample_vf %>%
  wilcox_test(vf ~ dog_group, p.adjust.method = "BH")%>% 
  filter(p.adj < 0.05)
```

Non-sig
```{r}
sample_vf %>%
  wilcox_test(vf ~ dog_group, p.adjust.method = "BH")%>% 
  filter(p.adj > 0.05)
```


## Size-function correlations

```{r size_function_correlation, warning=FALSE, comments="", message=FALSE}
sample_genome_size %>% 
  left_join(sample_amr %>% select(sample,AMR),by="sample") %>% 
  left_join(sample_vf %>% select(sample,vf),by="sample") %>% 
  left_join(alpha_div,by="sample") %>% 
  summarise(
    size_AMR = cor(size, AMR,  use = "complete.obs"),
    size_vf  = cor(size, vf,   use = "complete.obs"),
    size_richness  = cor(size, richness,   use = "complete.obs"),
    size_neutral  = cor(size, neutral,   use = "complete.obs"),
    size_phylogenetic  = cor(size, phylogenetic,   use = "complete.obs"),
    neutral_AMR = cor(neutral, AMR,   use = "complete.obs")
  )
```

```{r size_amr_correlation_plot, warning=FALSE, comments="", message=FALSE}
sample_genome_size %>%
  left_join(sample_amr %>% select(sample, AMR), by = "sample") %>%
  left_join(alpha_div, by = "sample") %>%
  ggplot(aes(x = size, y = AMR, color = country)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE, show.legend = FALSE) +
  theme_classic()
```

```{r size_amr_correlation_plot_group, warning=FALSE, comments="", message=FALSE}
sample_genome_size %>%
  left_join(sample_amr %>% select(sample, AMR), by = "sample") %>%
  left_join(alpha_div, by = "sample") %>%
  ggplot(aes(x = size, y = AMR, color = dog_group)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE, show.legend = FALSE) +
  theme_classic()
```

```{r}
df <- sample_genome_size %>% 
  left_join(sample_amr %>% select(sample, AMR), by = "sample") %>% 
  left_join(alpha_div, by = "sample")

cor.test(df$size, df$AMR, method = "spearman")

model <- lm(AMR ~ size, data = df)
summary(model)

model <- lm(AMR ~ size * country, data = df)
summary(model)

df %>%
  group_by(country) %>%
  do(tidy(lm(AMR ~ size, data = .))) %>% 
  filter(term=="size")%>% 
  filter(p.value<0.05)

df %>%
  group_by(dog_type) %>%
  do(tidy(lm(AMR ~ size, data = .))) %>% 
  filter(term=="size") 

model <- lm(AMR ~ size * dog_group, data = df)
summary(model)
```


```{r}
df <- sample_genome_size %>% 
  left_join(sample_vf %>% select(sample, vf), by = "sample") %>% 
  left_join(alpha_div, by = "sample")

cor.test(df$size, df$vf, method = "spearman")

model <- lm(vf ~ size, data = df)
summary(model)

model <- lm(vf ~ size * country, data = df)
summary(model)

df%>%
  group_by(country) %>%
  do(tidy(lm(vf ~ size, data = .))) %>% 
  filter(term=="size")%>% 
  filter(p.value<0.05)

df%>%
  group_by(dog_type) %>%
  do(tidy(lm(vf ~ size, data = .))) %>% 
  filter(term=="size")

model <- lm(vf ~ size * dog_group, data = df)
summary(model)
```

```{r}
genome_metadata %>% 
  filter(phylum=="Fusobacteriota") %>% 
  group_by(genus) %>% 
  summarise(count=n())
```

```{r zero_phylo_fuso, comment="",  message=FALSE, warning=FALSE}
genome_metadata %>%
  filter(genus %in% c("Fusobacterium_A","Fusobacterium_B")) %>% 
  dplyr::select(genome) %>% 
  nrow()

# MAGs reconstructed from sled dogs
genome_metadata %>%
  filter(genus %in% c("Fusobacterium_A","Fusobacterium_B")) %>% 
  filter(str_starts(genome, "GL") | str_starts(genome, "EHI") | str_starts(genome, "EHA"))

# MAGs reconstructed from the others
genome_metadata %>%
  filter(genus %in% c("Fusobacterium_A","Fusobacterium_B")) %>% 
  filter(!(str_starts(genome, "GL") | str_starts(genome, "EHI") | str_starts(genome, "EHA")))

fuso <- genome_metadata %>%
  filter(genus %in% c("Fusobacterium_A","Fusobacterium_B")) %>% 
   dplyr::select(genome) %>%
  pull()

genome_counts_filt_transposed <- genome_counts_filt %>%
  column_to_rownames("genome") %>% 
  t() %>% 
  as.data.frame()

genome_zeroRepl <- zCompositions::cmultRepl(genome_counts_filt_transposed, method = "GBM", output = "prop", z.warning = 0.95)

metadata_clr <- sample_metadata[sample_metadata$sample %in% rownames(genome_zeroRepl), ]

clr_transform <- function(x) {
  log(x) - mean(log(x), na.rm = TRUE)
}
genome_counts_clr <- data.frame(t(apply(genome_zeroRepl, 1, clr_transform)))

fuso_clr <- genome_counts_clr %>%
  rownames_to_column(., "sample") %>% 
  pivot_longer(-sample,
    names_to = "genome",
    values_to = "count"
  ) %>% 
  filter(genome %in% fuso) %>%
  left_join(
    metadata_clr %>% dplyr::select(sample, dog_type),
    by = "sample"
  ) 

fuso_clr %>% 
  group_by(dog_type) %>% 
  summarise(mean_fuso=round(mean(count),3), sd_fuso=round(sd(count),3)) %>% 
  mutate(Fusobacterium_abundance=str_c(mean_fuso,"±",sd_fuso)) %>% 
  dplyr::select(dog_type,Fusobacterium_abundance)

kruskal_test(count ~ dog_type, data=fuso_clr)

fuso_clr %>%
  wilcox_test(count ~ dog_type, p.adjust.method = "BH")
```



